name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    env:                                  
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
      HEROKU_API_KEY:   ${{ secrets.HEROKU_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r meddesk-backend/requirements.txt

      - name: Run Pytest
        run: |
          python -m pytest tests/tests.py

          # if tests pass it deploys below

      - name: Install Heroku CLI
        if: success()
        run: |
          curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
    
      - name: Set Heroku config vars
        if: success()
        run: |
          heroku config:set FLASK_SECRET_KEY="$FLASK_SECRET_KEY" \
                            DATABASE_URL="$DATABASE_URL" \
                            --app ${{ secrets.HEROKU_APP_NAME }}
      
      - name: Push to Heroku
        if: success()
        run: |
          heroku git:remote --app ${{ secrets.HEROKU_APP_NAME }}
          git push heroku HEAD:main --force